// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH7tYzolq3ooVcqzTiXitFPlZBjSxQG2k',
    appId: '1:336012408485:web:ec67e7b09598c41b237f4c',
    messagingSenderId: '336012408485',
    projectId: 'iitdelectronicsmarket',
    authDomain: 'iitdelectronicsmarket.firebaseapp.com',
    storageBucket: 'iitdelectronicsmarket.appspot.com',
    measurementId: 'G-7Z88G7KCDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjukPj6XrGZ974uVG_t478KcChcK_3c4',
    appId: '1:336012408485:android:0c2df38015d0b240237f4c',
    messagingSenderId: '336012408485',
    projectId: 'iitdelectronicsmarket',
    storageBucket: 'iitdelectronicsmarket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3b36tcZg_3cUF9Uw_jT5HN38wcgaD_4',
    appId: '1:336012408485:ios:8a21e52f2052ed7a237f4c',
    messagingSenderId: '336012408485',
    projectId: 'iitdelectronicsmarket',
    storageBucket: 'iitdelectronicsmarket.appspot.com',
    iosClientId: '336012408485-rf5mamm22d814ehk5e566prk57qelsi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa3b36tcZg_3cUF9Uw_jT5HN38wcgaD_4',
    appId: '1:336012408485:ios:6557841d09686552237f4c',
    messagingSenderId: '336012408485',
    projectId: 'iitdelectronicsmarket',
    storageBucket: 'iitdelectronicsmarket.appspot.com',
    iosClientId: '336012408485-bl63j9q7on456dvp7kqv81d6cmsth6fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
